# Libraries

In [1]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt


from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.utils        import *
from pkg.algorithims  import multimodal

# Objeto evaluacion

In [2]:
ev = Evaluation()

# Algoritmo Genetico Multimodal

## Parametros del algoritmo

In [3]:
# tamaño poblacion, igual que en AG basico
tama = 24

- distancia de hamming (implementada)
- tamaño poblacion: igual que agb (24 cromosomas)
- Mantener misma mutacion que en el algoritmo basico
- AG multimodal espacial
- Clearing de 5 nichos
- Determinar radio adecuado, basado en distancia de hamming

In [4]:
poblacion = inicializa_poblacion(26)

In [5]:
f_poblacion, km, slots = evalua_poblacion(poblacion, ev, 9)

In [6]:
pob = aclarado(poblacion, f_poblacion, 10, 4)

# Algoritmo

# Ajuste de parametros

**Radio de nicho**

Importante un buen ajuste porque:
- si es un valor muy pequeño: no afecta al hacer el aclarado
- Si es un valor muy alto: penalizará a todos los individuos

Estudiamos todos los valores posibles (de 1 a 15), teniendo en cuenta que si el radio fuese 16, significa que serian dos cromosomas totalmente diferentes.

In [86]:
valores_radio = list(range(1,15))

In [95]:
for i in valores_radio:
    radio = valores_radio[i]
    crom, fit, media = multimodal(24, 9, ev, 1, radio, 4)

    print(f'para radio {i} obtiene poblacion nueva de {media}')

24
24
24
24
24
24
24
24
para radio 1 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 2 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 3 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 4 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 5 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 6 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 7 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 8 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 9 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 10 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 11 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 12 obtiene poblacion nueva de 24.0
24
24
24
24
24
24
24
24
para radio 13 obtiene poblacion nueva de 24.0


IndexError: list index out of range

La experimentación para escoger el valor del radio no ha arrojado resultados concluyentes, por lo que determinamos establecemos el valor a 8. Valor intermedio, esperando encontrar un compromiso entre afectar a toda la población y penalizar a toda la población.

# EXPERIMENTACIÓN

In [3]:
# Parametros obtenidos en ag basico
alpha = 9
tama_poblacion = 24

# semillas utilizadas en todos los algoritmos
seeds = np.array([7054, 1354, 23503, 11268, 58283])



Obtenemos los datos con los que elaboraremos las tablas comparativas y extraeremos conclusiones.

In [4]:
costs       = np.array([])
evaluations = np.array([])
slots       = np.array([])

for s in seeds:

    # set evauation calls counter to 0
    ev.total_calls = 0

    np.random.seed(s)

    
    crom, fit = multimodal(
        tama_poblacion  = tama_poblacion,
        alpha           = alpha,
        evaluation      = ev,
        saltos_aclarado = 5,
        kappa           = 4,
        radio           = 8,
        grafica         = False
    )

    print(crom)
    print(fit)

    value, total_distance, slot = ev.fitness(crom,alpha)
    
    costs       = np.append(costs, total_distance)
    evaluations = np.append(evaluations, ev.total_calls)
    slots       = np.append(slots, slot)


df = pd.DataFrame({
    "ev_medias"    : [evaluations.mean()],
    "ev_mejor"     : [evaluations.min()],
    "ev_std"       : [evaluations.std()],
    "coste_medio"  : [costs.mean()],
    "coste_mejor"  : [costs.min()],
    "coste_std"    : [costs.std()],
    "slots_medio"  : [slots.mean()],
    "slots_min"    : [slots.min()],
    "slots_std"    : [slots.std()]
})

df_2 = pd.DataFrame({
    'Ejecución'    : [1,2,3,4,5],
    "Coste mejor"  : costs,
    "Evaluaciones" : evaluations,
    "slots"        : slots
})

[21 12 15 17 17 13 13  8 12 16 15 23  3 14 10 14]
2357.8777236381175
[17 11 15 20 20 14 12  9 12 17 16 24  2 16  5 13]
2352.218693395007
[14 12 18 18 19 14 14  6 13 19 18 24  2 15  6 11]
2356.3733836870265
[12 14 15 16 19 11 13 18 12 23 14 20  5  6 15 11]
2378.7693415370095
[13 12 12 18 20 13 12 12 12 20 17 26  3 13 10 10]
2359.5073764541867


In [5]:
df

ev_medias  ev_mejor      ev_std  coste_medio  coste_mejor  coste_std  \
0     2711.4    1361.0  879.773062   352.149304   345.218693   5.835571   

   slots_medio  slots_min  slots_std  
0        223.2      223.0        0.4

In [6]:
df_2

Ejecución  Coste mejor  Evaluaciones  slots
0          1   350.877724        2849.0  223.0
1          2   345.218693        2897.0  223.0
2          3   349.373384        4081.0  223.0
3          4   362.769342        1361.0  224.0
4          5   352.507376        2369.0  223.0

In [7]:
df.to_excel('./01_stats_p2/multimodal_stats.xlsx')
df_2.to_excel('./01_stats_p2/multimodal_ejecuciones.xlsx')