# Libraries

In [1]:
import numpy as np

from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.utils        import *
from pkg.algorithims  import local_search

# VNS

In [2]:
seeds = np.array([7054, 1354, 23503, 11268, 58283])
ev    = Evaluation()

granularity = 2 # calculada previamente

In [3]:
solution = generate_random_solution()
k = 4

print(solution)

neighbor = neighbor_generation_operator(
    solution = solution, 
    k        = k
)

print(neighbor)

[ 8 23 20 11  8  6 14 11 17 11 23  6 23 14 11 14]
[ 6 17  8 23 11 23 23 11 14 11 11 14 20 14  6  8]


In [7]:
# local_search(granularity, evaluation, initial_sol = None, path=None)

np.random.seed(seeds[4])

# generate random solution
global_sol      = generate_random_solution()
global_sol_cost = ev.evaluate(global_sol)


k  = 1
bl = 0
bl_max = 20 # criterio de salida. Calcular en funcion de la experimentacion

while k <= k_max and bl <= bl_max :

    neighbor = neighbor_generation_operator(
        solution = global_sol, 
        k        = k
    )

    candidate_sol, candidate_sol_cost = local_search(
        granularity = granularity,
        evaluation  = ev,
        initial_sol = neighbor
    )

    bl += 1
    print(bl)

    if candidate_sol_cost < global_sol_cost:
        print(f'mejora')
        print(f'Coste antiguo: {global_sol_cost}')
        print(f'Coste nuevo: {candidate_sol_cost}')
        global_sol      = candidate_sol
        global_sol_cost = candidate_sol_cost

        k = 1
    else:
        print('no mejora')
        k += 1

print(global_sol_cost)
print(global_sol)



1
mejora
Coste antiguo: 494.99265776674383
Coste nuevo: 414.1047597059338
2
no mejora
3
mejora
Coste antiguo: 414.1047597059338
Coste nuevo: 409.6756059650655
4
no mejora
5
no mejora
6
no mejora
7
no mejora
409.6756059650655
[16 10 18 20 20 14 12 12 12 14 10 24  2 18  2 12]
