# Libraries

In [1]:
import numpy as np

from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.utils        import *
from pkg.algorithims  import local_search

Dudas:

- valor de bl_max? bl

- debemos ajustar el valor de bl_max? mediante experimentacion?

# VNS

In [2]:
seeds = np.array([7054, 1354, 23503, 11268, 58283])
ev    = Evaluation()

granularity = 2 # calculada previamente

In [3]:
solution = generate_random_solution()
k = 4

print(solution)

neighbor = neighbor_generation_operator(
    solution = solution, 
    k        = k
)

print(neighbor)

[17 17 22  7  5  7 15 12 15 15 12 22 20 15 12  5]
[15 22 12 22  5 12 15 15 20 17 17 12 15  7  5  7]


In [6]:
# local_search(granularity, evaluation, initial_sol = None, path=None)

np.random.seed(seeds[0])

# generate random solution
global_sol      = generate_random_solution()
global_sol_cost = ev.evaluate(global_sol)


k  = 1
bl = 0
bl_max = 20

while k <= k_max and bl <= bl_max :

    neighbor = neighbor_generation_operator(
        solution = global_sol, 
        k        = k
    )

    candidate_sol, candidate_sol_cost = local_search(
        granularity = granularity,
        evaluation  = ev,
        initial_sol = neighbor
    )

    bl += 1
    print(bl)

    if candidate_sol_cost < global_sol_cost:
        print(f'mejora')
        print(f'Coste antiguo: {global_sol_cost}')
        print(f'Coste nuevo: {candidate_sol_cost}')
        global_sol      = candidate_sol
        global_sol_cost = candidate_sol_cost

        k = 1
    else:
        print('no mejora')
        k += 1

print(global_sol_cost)
print(global_sol)



1
mejora
Coste antiguo: 564.9951766145007
Coste nuevo: 375.15261936180923
2
mejora
Coste antiguo: 375.15261936180923
Coste nuevo: 374.2942479149146
3
no mejora
4
no mejora
5
no mejora
6
mejora
Coste antiguo: 374.2942479149146
Coste nuevo: 373.9783525025424
7
no mejora
8
mejora
Coste antiguo: 373.9783525025424
Coste nuevo: 373.4942826545511
9
mejora
Coste antiguo: 373.4942826545511
Coste nuevo: 373.03445225832417
10
mejora
Coste antiguo: 373.03445225832417
Coste nuevo: 372.1944671808838
11
no mejora
12
no mejora
13
mejora
Coste antiguo: 372.1944671808838
Coste nuevo: 371.51420862258544
14
no mejora
15
no mejora
16
no mejora
17
no mejora
371.51420862258544
[15 12 20 15 20 14  9 13 12 14 12 24  2 13 13 12]
