# Libraries

In [2]:
import numpy as np

from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.utils        import *
from pkg.algorithims  import local_search

# Generación población inicial

Número par de individuos. Probamos con distintos tamaños: 18, 22, 26, 30.

In [13]:
tam_poblacion = np.array([18,22,26,30])

En cada población añadimos 3 cromosomas conocidos con buenas heurísticas, calculados previamente con otros algoritmos (práctica 1)
- [16 12 19 17 20 13 12 11 10 13 14 24  2  2 22 13] -> 375.7658566586277
- [16 12 20 18 20 13 12 11  9 15 14 24  2 16  6 12] -> 378.2038511496476
- [13 12 20 21 17 14 14  8 11  8 17 24  3 11 14 13] -> 381.8566495953962

Estos cromosomas se han evaluado según la función coste (antigua), y no sobre la función fitness (nueva).

In [31]:
conocido1 = np.array([16, 12, 19, 17, 20, 13, 12, 11, 10, 13, 14, 24,  2,  2, 22, 13])
conocido2 = np.array([16, 12, 20, 18, 20, 13, 12, 11,  9, 15, 14, 24,  2, 16,  6, 12])
conocido3 = np.array([13, 12, 20, 21, 17, 14, 14,  8, 11,  8, 17, 24,  3, 11, 14, 13])

conocidos = np.array([conocido1, conocido2, conocido3])

In [35]:
def inicializa_poblacion(tam, conocidos=None):

    if conocidos is None:
        cromosoma = generate_random_solution()
        poblacion = np.array([cromosoma])
    else:
        poblacion = conocidos
    

    for i in range(tam_poblacion[1]- poblacion.shape[0]):
        cromosoma = generate_random_solution()
        poblacion = np.append(poblacion,[cromosoma],0)  
    
    return poblacion

In [38]:
poblacion = inicializa_poblacion(tam_poblacion<[0], conocidos)
print(poblacion)

for i in range(poblacion.shape[0]):
    c = poblacion[i,:]
    print(f'{c} total slots: {sum(c)}')

[[16 12 19 17 20 13 12 11 10 13 14 24  2  2 22 13]
 [16 12 20 18 20 13 12 11  9 15 14 24  2 16  6 12]
 [13 12 20 21 17 14 14  8 11  8 17 24  3 11 14 13]
 [ 6 14  8 17 25  8 17 14 25 14 11 14 14  8 19  6]
 [12 12 17  5 12 17 15  5 17 15 12 22 12 10 20 15]
 [20 20  5 17  7 17  5 17  7 22  7 10  5 17 22 22]
 [ 9 24 25  9 12 24  6 12 12  6 27 15  6  6 12 15]
 [20 10 22 12 22 17 17 10 10  7 12 22 15  7  7 10]
 [ 5 16 16  9  9 12 14 12 16 21 21 12 12 12 19 14]
 [17 11 17  4  4 15 15 15  9 19 17 19 17 11 17 13]
 [12 10 20 15 17 12 15 12 17 17 17  7 12 10 10 15]
 [ 8 19 21  6  6 22  6  6  6 22 19 11 14 19 19 16]
 [15 15 20  5 10 15 15 17  7 20 17 10  5 22  7 20]
 [10 10 13 13 16 23 10 10 18  5  5 13 16 21 13 23]
 [15 18 19 10 20  5 13 18 10 20 20  5 13 13 13  8]
 [15  9 13  7 15 17 17 20 15  9 11 15 20 13 13 11]
 [ 9  9 14  9 20 12 17  6  6 14 23 26 17  6 12 20]
 [ 5  7 14 20  9 16 12 19 19  5 19  9 19 21  7 19]
 [17 15 19  5 10 10 20 17 15 10 15  5 20  7 20 15]
 [20 17 17 17 14  6  6  6 23  8

In [29]:

# print(poblacion)

# numero de cromosomas conocidos
poblacion.shape[0] 


for i in range(tam_poblacion[1]- poblacion.shape[0]):
    cromosoma = generate_random_solution()
    poblacion = np.append(poblacion,[cromosoma],0)

print(poblacion)

for i in range(poblacion.shape[0]):
    cromosoma = poblacion[i,:]
    print(sum(cromosoma))

poblacion.shape


[[16 12 19 17 20 13 12 11 10 13 14 24  2  2 22 13]
 [16 12 20 18 20 13 12 11  9 15 14 24  2 16  6 12]
 [13 12 20 21 17 14 14  8 11  8 17 24  3 11 14 13]
 [20 13 13  9 16 13 20 18  9  9 20 20 11  7 18  4]
 [ 9 19  7 20  9 20  9 18 18  4  7 16 13 13 18 20]
 [ 5 23  8  8  8  8  8 13 24 24 21 13 19 11 16 11]
 [ 9  7 18 18 18 20 18  4 13 20 13 11 16 11 13 11]
 [11 13 11  7 18 13 13 20 20 20 15 11 13 15 15  4]
 [20  7 18  7  7 18 18 16 16 21 14  5 18 14 16  5]
 [ 5  8 20 18 22 18 12 22 20  5 12  5  5 22  8 18]
 [19 17 11  7 11 13 15  9 20 11  9  7 17 17 20 17]
 [ 7  5 20 17 19 19 21  7  5 21 12  5 17 19  7 19]
 [16  8  8  5 24  5 18 21 18 10 16  5  8 21 13 24]
 [13 18 22  5 20  5 18  8 10  5  8 20 15 10 23 20]
 [20 12 10 15 20 12 22 15 10 15  8  5 10 15 12 18]
 [ 4 17 11 20  9 17 15 13  4 20 15 17  4 13 20 20]
 [18 18 16 14 11 18 21  7 21 11  5  7 21 11  5 16]
 [ 9  9 23 18 12  9 12 15 12 23 15 12  9 12  9 21]
 [ 4 10 14 16 18 18 16 12 18 16 18  4  8 18 16 12]
 [ 7 10 20 20 10 20 15 17 15 20

(22, 16)

In [30]:
poblacion = np.array([])
poblacion.shape
poblacion = np.append(poblacion,[conocido1],0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

# Funciones necesarias

Partimos de una población inicial aleatoria a la que incorporamos 3 cromosomas conocidos, que bajo la función de coste de la práctica 1, presentaban buenas caracteristicas.

# Algoritmo Genético Básico (Estacionario)

Modelo estacionario: Durante cada iteración se crea una población completa con nuevos individuos, que reemplaza a la anterior.

# Algoritmo Genético Básico (Generacional)

Durante cada iteración, se escogen 2 padres de la población y se les aplica los operadores genéticos.

El/los descendientes reemplazan a uno/dos cromosoma/s de la población inicial.

Presión selectiva alta (enfoque está muy dirigido a reproducir los mejores individuos y eliminar los peores de la población). Produce una convergencia rápida cuando se reemplazan los peores cromosomas de la población.

Élite de 5 individuos

In [ ]:
# pseudo del algoritmo genetico
t = 0
poblacion    = inicializa_poblacion(tama, conocidos)
evaluaciones = evaluar_poblacion()
while condicion == True:
    t += 1
    padres = seleccionar_padres(P)
    hijos = cruce(padres)
    hijos_mutados, ev_hijos_mutados = mutacion(hijos)