# Libraries

In [4]:
import numpy as np

from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.algorithims  import *

from time import time

# Busqueda Local

Primer mejor vecino

In [5]:
seeds = np.array([7054, 1354, 23503, 11268, 58283])
ev = Evaluation()

## Estudio de la granularidad

Previamente estudiada en la práctica anterior.

In [6]:
granularidad = 2

## Experimentación

In [7]:
costs       = np.array([])
evaluations = np.array([])
slots       = np.array([])

for s in seeds:

    # set evauation calls counter to 0
    ev.total_calls = 0

    np.random.seed(s)

    solution, cost = local_search(
        granularity = granularidad,
        evaluation  = ev,
        # path = './01_stats/local_search_' + str(s) + '.xlsx'
    )

    print(solution)
    print(cost)
    
    costs       = np.append(costs, cost)
    evaluations = np.append(evaluations, ev.total_calls)
    slots       = np.append(slots, solution.sum())


df = pd.DataFrame({
    "ev_medias"    : [evaluations.mean()],
    "ev_mejor"     : [evaluations.min()],
    "ev_std"       : [evaluations.std()],
    "coste_medio"  : [costs.mean()],
    "coste_mejor"  : [costs.min()],
    "coste_std"    : [costs.std()],
    "slots_medio"  : [slots.mean()],
    "slots_min"    : [slots.min()],
    "slots_std"    : [slots.std()]
})

df_2 = pd.DataFrame({
    'Ejecución'    : [1,2,3,4,5],
    "Coste mejor"  : costs,
    "Evaluaciones" : evaluations,
    "slots"        : slots
})

[16 12 19 17 20 13 12 11 10 13 14 24  2  2 22 13]
375.7658566586277
[16 12 20 18 20 13 12 11  9 15 14 24  2 16  6 12]
378.2038511496476
[12  8 20 14 20 12 13 12 10 12 13 24  4 12 19 13]
398.7077088119181
[13 12 20 21 17 14 14  8 11  8 17 24  3 11 14 13]
381.8566495953962
[16 10 18 14 20 14 12 12 12 14 10 24  2 12 14 12]
409.6756059650655


In [8]:
df

ev_medias  ev_mejor     ev_std  coste_medio  coste_mejor  coste_std  \
0      892.6     507.0  227.19912   388.841934   375.765857  13.147792   

   slots_medio  slots_min  slots_std  
0        218.8      216.0        1.6

In [9]:
df_2

Ejecución  Coste mejor  Evaluaciones  slots
0          1   375.765857         991.0  220.0
1          2   378.203851        1176.0  220.0
2          3   398.707709         993.0  218.0
3          4   381.856650         507.0  220.0
4          5   409.675606         796.0  216.0

In [10]:
df.to_excel('./01_stats_p2/bl_ejecuciones.xlsx')
df_2.to_excel('./01_stats_p2/bl_stats.xlsx')