# Libraries

In [5]:
import numpy             as np
import pandas            as pd
import matplotlib.pyplot as plt


from pkg.constants    import *
from pkg.evaluation   import Evaluation
from pkg.utils        import *
from pkg.algorithims  import chc

# Objeto evaluacion

In [6]:
ev = Evaluation()

# Funciones necesarias

## Distancia de Hamming

Calcula la cantidad de genes que se diferencian entre 2 cromosomas, es decir, cuántas posiciones tienen alelos distintos.

In [7]:
padre1 = generate_random_solution()
padre2 = generate_random_solution()

padre1, padre2

(array([14, 20, 17,  5, 12, 12, 12, 22,  7, 12, 17, 10, 14, 22, 19,  5],
       dtype=int64),
 array([ 5, 16, 11,  8, 21, 24, 24, 21,  5,  8, 19,  8, 19,  5,  8, 16],
       dtype=int64))

In [5]:
distancia_hamming(padre1,padre2)

15

## Operador de cruce

Los cruces en CHC se hacen cambiando exactamente la mitad de los elementos que son distintos en ambos padres y luego se aplica Parent Centered.

### Cruce Parent Centered

1. Selección de los genes a mutar
2. Mutación gaussiana del valor intercambiado.

Mutación gaussiana: Dado un cromosoma p con un gen seleccionado para la mutación i, se le aplica una distribución normal de media el valor a mutar y desviación estandar 2, para que el 68% de las mutaciones estén entre media-2 y media+2

In [8]:
cruce_parent_centered(padre1, padre2)

(array([14, 14, 17,  5, 21, 12, 23, 21,  7,  9, 16,  6, 22, 22, 19,  5],
       dtype=int64),
 array([14, 16, 16,  8, 21, 12, 24, 21,  8,  8, 19,  8, 19, 23, 22,  8],
       dtype=int64))

# Experimentación

In [9]:
np.random.seed(0)

ev.total_calls = 0

cromosoma, fitness = chc(26, 9, 3, ev, True)

rearranque: 0
iteracion: 0
rearranque: 0
iteracion: 1
rearranque: 0
iteracion: 2


KeyboardInterrupt: 