# LIBRARIES

In [1]:
import pandas as pd
import numpy as np
from pkg.constants import *
from pkg.greedy import greedy
from pkg.evaluation import Evaluation
from time import time
from pkg.utils import *
from pkg.random_search import random_search
from itertools import permutations
from pkg.neighborhood import Neighborhood
from pkg.local_search import local_search


# GENERACIÓN DE SEMILLAS
Las semillas deben guardarse para poder repetir las ejecuciones y comparar resultados

In [2]:
# seeds = np.random.randint(0,99999,SEEDS)
# print(seeds)

# seeds = [12345, 54321, 12221, 22211, 22212] # Semillas adri
seeds = np.array([12345, 54321, 12221, 22211, 22212])
print(seeds)

[12345 54321 12221 22211 22212]


# CREACION OBJETO EVALUATION

In [3]:
evaluation = Evaluation()

# SOLUCIÓN GREEDY

## LECTURA DE DATOS

In [39]:
deltas_df   = pd.read_csv(DELTAS_5M_PATH) 
deltas_matrix   = deltas_df.to_numpy()

## GENERA SOLUCION 

In [40]:
initial_state = deltas_matrix[0,:]
greedy_sol = greedy(initial_state)
greedy_sol.sum()

220.0

## EVALUA SOLUCION

In [41]:
# 574.5513854177129
evaluation.evaluate(greedy_sol)

574.5513854177129

# BUSQUEDA ALEATORIA

### ALGORITMO

In [6]:
best_solution_per_seed = np.empty((SEEDS, TOTAL_STATIONS))


for i in range(SEEDS):
    np.random.seed(seeds[i])
    best_solution_per_seed[i,:] = random_search(evaluation = evaluation)


In [7]:
print(best_solution_per_seed)
print(evaluation.evaluate(best_solution_per_seed[0,:]))
print(evaluation.evaluate(best_solution_per_seed[1,:]))
print(evaluation.evaluate(best_solution_per_seed[2,:]))
print(evaluation.evaluate(best_solution_per_seed[3,:]))
print(evaluation.evaluate(best_solution_per_seed[4,:]))


[[22. 12. 12. 14. 14. 14. 14. 17. 14. 17.  5. 17.  5. 12. 19. 12.]
 [18. 16. 14. 16. 14.  7. 14. 19. 11. 20. 16. 20. 14. 11.  5.  5.]
 [14. 16.  9. 16. 16.  9. 20. 19. 16.  9. 14. 21.  5.  5. 12. 19.]
 [18.  6. 12. 12. 12. 22. 15. 12.  6. 18. 15. 21.  6. 21.  6. 18.]
 [20. 10. 10. 13. 21.  5.  8. 13.  8. 16. 16. 21. 10. 10. 21. 18.]]
451.4466908526273
456.52281659203965
446.1530703628353
449.3685204131469
444.49777670070273


# BUSQUEDA LOCAL: EL PRIMER MEJOR VECINO

## Generación soluciones iniciales

In [4]:
seeds

array([12345, 54321, 12221, 22211, 22212])

## Algoritmo


In [6]:
for i in range(SEEDS):

    np.random.seed(seeds[i])

    sol = local_search(
        slots_to_move = 1,
        evaluation    = evaluation
    )
    
    print(sol)
    print(evaluation.evaluate(sol))

    

[17. 12.  8. 14. 20.  6. 12. 11. 17. 10. 17. 18. 19.  7. 12. 19.]
451.746201350656
[10.  7. 12. 14. 15.  2. 14. 10. 10. 23. 23. 19. 15.  5. 18. 23.]
439.6052159797899
[12.  8. 18. 18. 18.  6. 12.  4. 10.  8. 22. 24. 10. 14. 19. 17.]
420.7960758264853
[16.  6. 19. 18. 20. 14. 12. 10. 12.  8. 10. 16. 10. 24.  9. 12.]
467.50906136064225
[17. 12. 21. 14. 20. 14. 12. 12. 10. 14. 12. 24. 11.  6.  8. 12.]
406.1600032194599


# ANOTACIONES DIA 21/03/2022

Dia 4: defensa de la práctica
la bsuqueda  tabu deberá tardar más o menos lo que tarda el enfriamiento simulado.
No tenemos en cuenta si los vecinos se repiten o no (no lo combprobamos.)
velocidad de movimiento: 5 (nos dice cuantas posibilidades hay)
matriz de frecuencias: como se hace??? 
greedy: queremos hacer algo inversamente prorporcional a lo que ha salido (hacemos la inversa de cada casilla de la matriz de frecuencias???) y luego normalizo (?)
ruleta de probabilidad inversa -> buscar libreria, que seguro que está hecho en algun lado. Si no, está el pseudo en la práctica.

la condicion de parada: que sea mayor o igual al numero de iteraciones 
generar vecinos tiene la restriccion tabu
cogemos el algoritmo de busqueda local y vmos añadiendo trocitos
la parte que suele generar más dudas suele ser la parte del greedy


granular: tamaño de movimiento de huecos entre estaciones